project:
  type: website
  resources:
    - profile-dark.jpg
  pre-render: _pre-render.py

website:
  title: "Paul Vernus"
  site-url: https://pvernus.github.io
  navbar:
    background: "#F4F4F4"
    foreground: "dark"
    search: false
    llms-txt: true
    right:
      - cv.qmd
      - garden.qmd
      - text: "Help"
        href: blog/index.qmd
  page-footer:
    right:
      - text: "Colophon"
        href: colophon.qmd

format:
  html:
    theme:
      light: [journal, brand]
      dark: [darkly, brand]
    css: styles.css
    toc: false
